#!/usr/bin/env python3
"""
apply-2026-09-04.py — Radium Command Center board patch
Generated by the daily Claude PLG run, evening of 3 Sep 2026 (00:0x UTC 4 Sep).

Evidence base: four Radium meetings on 3 Sep (Fireflies), HubSpot portal 244452220,
Contentsquare project 921964.

Contract with scripts/watch-patches.js:
  - filename matches ^apply-\\d{4}-\\d{2}-\\d{2}\\.py$ and sits in the REPO ROOT
  - the watcher backs up dashboard-data.json to .bak, then runs: python3 <file> --write
    with cwd = repo root, then `npm run build`, then moves this file to
    scripts/processed-patches/
  - a non-zero exit makes the watcher restore its backup and mark the patch .failed

This script writes its OWN timestamped backup and deliberately does not touch
dashboard-data.json.bak, so the watcher's rollback copy stays intact.

Usage:
  python3 apply-2026-09-04.py            # dry run, prints the plan, writes nothing
  python3 apply-2026-09-04.py --write    # applies

Idempotent: every change is guarded, so a second run reports skips and changes nothing.
"""

import hashlib
import json
import os
import re
import shutil
import sys
from datetime import datetime, timezone

DATA = os.path.join("public", "data", "dashboard-data.json")
TODAY = "2026-09-04"
STAMP = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")

WRITE = "--write" in sys.argv

changes = []
skips = []


# ── helpers ──────────────────────────────────────────────────────────────────
def all_tasks(doc):
    for m in doc["milestones"]:
        for e in m["epics"]:
            for t in e["tasks"]:
                yield m, e, t


def find_task(doc, tid):
    for _m, _e, t in all_tasks(doc):
        if t["id"] == tid:
            return t
    return None


def epic_of(doc, anchor_tid):
    """Locate an epic by the epic that CONTAINS a known task id.

    Never by epic id or name, so renames and reorders cannot misfile a task.
    """
    for _m, e, t in all_tasks(doc):
        if t["id"] == anchor_tid:
            return e
    return None


def tick(doc, tid, why):
    t = find_task(doc, tid)
    if t is None:
        skips.append(f"{tid}: NOT FOUND — tick skipped")
        return
    if t["completed"]:
        skips.append(f"{tid}: already ticked done")
        return
    t["completed"] = True
    t["completedAt"] = STAMP
    changes.append(f"{tid}: ticked done — {why}")


def set_priority(doc, tid, old, new, why):
    t = find_task(doc, tid)
    if t is None:
        skips.append(f"{tid}: NOT FOUND — priority change skipped")
        return
    if t["priority"] == new:
        skips.append(f"{tid}: priority already {new}")
        return
    if t["priority"] != old:
        skips.append(
            f"{tid}: priority is {t['priority']!r}, expected {old!r} — LEFT ALONE (Leo may have changed it)"
        )
        return
    t["priority"] = new
    changes.append(f"{tid}: priority {old} -> {new} — {why}")


def append_note(doc, tid, marker, note):
    """Append a dated line. Never overwrites. `marker` makes it idempotent."""
    t = find_task(doc, tid)
    if t is None:
        skips.append(f"{tid}: NOT FOUND — note skipped")
        return
    if marker in t["description"]:
        skips.append(f"{tid}: note already present")
        return
    sep = "" if t["description"].endswith((" ", "\n")) else " "
    t["description"] = t["description"] + sep + note
    changes.append(f"{tid}: appended dated note")


def add_task(doc, anchor, task):
    e = epic_of(doc, anchor)
    if e is None:
        skips.append(f"{task['id']}: anchor {anchor} NOT FOUND — task NOT added")
        return
    if find_task(doc, task["id"]) is not None:
        skips.append(f"{task['id']}: already exists")
        return
    for t in e["tasks"]:
        if t["title"].strip().lower() == task["title"].strip().lower():
            skips.append(f"{task['id']}: a task with this title already exists ({t['id']})")
            return
    e["tasks"].append(task)
    changes.append(f"{task['id']}: added to epic {e['id']} ({e['title']}) — {task['title']}")


def T(tid, title, desc, assignee, priority, due, tags, channel, bucket):
    return {
        "id": tid,
        "title": title,
        "description": desc,
        "completed": False,
        "assignee": assignee,
        "priority": priority,
        "dueDate": due,
        "tags": tags,
        "channel": channel,
        "bucket": bucket,
    }


# ── load ─────────────────────────────────────────────────────────────────────
if not os.path.exists(DATA):
    print(f"ERROR: {DATA} not found. Run this from the repo root.")
    sys.exit(1)

with open(DATA, encoding="utf-8") as f:
    doc = json.load(f)

before_count = sum(1 for _ in all_tasks(doc))
print(f"Loaded {DATA} — lastUpdated={doc['lastUpdated']}, {before_count} tasks\n")


# ── 0. scrub ─────────────────────────────────────────────────────────────────
# An earlier build of this patch appended a withdrawn note to the four tasks below.
# Those notes were appended, so each is the tail of its description and begins with
# the marker. Strip it. No-op if that build never ran here. This patch adds no
# "Update 3 Sep: " note to any of these four, so nothing legitimate is at risk.
SCRUB_IDS = ("T112", "T094", "T133", "T134")
SCRUB = re.compile(r"\s*Update 3 Sep: .*$", re.S)


def scrub_task(t):
    cleaned = SCRUB.sub("", t["description"]).rstrip()
    if cleaned == t["description"]:
        return False
    t["description"] = cleaned
    return True


for tid in SCRUB_IDS:
    t = find_task(doc, tid)
    if t is not None and scrub_task(t):
        changes.append(f"{tid}: removed withdrawn note from description")


# ── 1. tick done ─────────────────────────────────────────────────────────────
tick(
    doc,
    "T097",
    "the session ran today 18:00 UTC for 52 minutes with Grace Morgan; keywords were "
    "pruned live, ~76 account-level negatives are now in place, and high-intent terms "
    "were reopened to phrase match (Fireflies 01M1F304TY1ARBKKWACQK1J7N4)",
)


# ── 2. priority ──────────────────────────────────────────────────────────────
set_priority(
    doc,
    "T129",
    "medium",
    "high",
    "Mona named the absence of published proof as the primary acquisition blocker today; "
    "Telus is the only real deployment and this is the only task that turns it into "
    "publishable proof",
)


# ── 3. dated notes ───────────────────────────────────────────────────────────
append_note(
    doc,
    "T019",
    "Update 3 Sep (eve): usage data has started landing",
    "Update 3 Sep (eve): usage data has started landing, the key-creation timestamp has not. "
    "HubSpot now carries real non-zero lifetime values on the same 29 contacts that hold API keys - "
    "input_tokens_lifetime, output_tokens_lifetime, requests_lifetime and spend_lifetime. "
    "Mona confirmed the source on the Adam Rogers sync: 'engineering just started making that "
    "available like this week', where before there was only credit consumption and it was not "
    "refreshed daily. But the trailing windows are a shell - input_tokens_7d/30d/90d are populated "
    "on 5,527 contacts with every single value zero, and output_tokens_7d/30d and requests_7d/30d "
    "are entirely empty. first_api_key_created_date is still 0 records and first_api_request_date "
    "still 3, unchanged for a third consecutive check. Of the six events, signup and api_key_created "
    "are effectively there, usage volume is there in lifetime form only, and the two timestamps that "
    "T061 and T032 actually need are not. "
    "source: Fireflies 01M1KS84P75ZB12RAEWT5BMRSN, HubSpot portal 244452220",
)

append_note(
    doc,
    "T061",
    "Update 3 Sep: the conversion switch now has a nearer path",
    "Update 3 Sep: the conversion switch now has a nearer path that does not wait on this task. "
    "On today's Google session, signup and enhanced conversions are fully live via Google Tag "
    "Manager - Mona fixed the tag with Google's tracking support on Tuesday and it is being "
    "monitored for seven days. MQLs are now arriving and attributable to individual search terms. "
    "Grace set the rule at 20-30 MQLs per campaign before signup comes off as a primary conversion "
    "action, put the full switch roughly two weeks out, and set a checkpoint on the Tuesday 8 Sep "
    "call where Mona expects to be past 20. Expect a 15-20% lift in attributed conversions once "
    "enhanced conversions completes. Note that path optimises to MQL, not to first token. This task "
    "stays blocked for the token version: first_api_request_date is still populated on 3 records. "
    "source: Fireflies 01M1F304TY1ARBKKWACQK1J7N4",
)

append_note(
    doc,
    "T090",
    "Update 3 Sep: Mona put a number and a doubt on this",
    "Update 3 Sep: Mona put a number and a doubt on this. There are 22 activated users, every one of "
    "them on the automatic $25 signup credit and none of them on a credit card. Her concern, raised "
    "on the Adam Rogers sync: '$25... now I'm starting to think it's too much. Because they're able "
    "to actually test a full workload on that.' She compared it to Clay's trial, which deliberately "
    "constrains volume so the trial cannot substitute for the product. Raised, not decided, and no "
    "owner was named on the call. source: Fireflies 01M1KS84P75ZB12RAEWT5BMRSN",
)

append_note(
    doc,
    "T120",
    "Update 3 Sep: Google's asset report says this is the highest-signal thing",
    "Update 3 Sep: Google's asset report says this is the highest-signal thing on the page. The 'Our "
    "models' site link is the strongest performing asset in the account - Grace: 'people are clearly "
    "interested in knowing specifically what your models look like compared to competitors' - and she "
    "recommends it on every ad. 'OpenAI compatible' as a headline drove 3 MQLs, and 'best balance of "
    "speed and cost' as a description carries the highest click-through rate in the account. The "
    "comparison is what converts; this table is the owned version of it. "
    "source: Fireflies 01M1F304TY1ARBKKWACQK1J7N4",
)

append_note(
    doc,
    "T113",
    "Update 3 Sep (eve): figures refreshed",
    "Update 3 Sep (eve): figures refreshed for 28 Aug - 3 Sep. /agents took 1,396 visits and 58.3% of "
    "all landings against 8.4% the prior week, at 91.4% bounce, 90.1% exit and a 15.4% scroll rate. "
    "The homepage fell to 858 visits and 34.8% of landings. Site bounce is 85.3% against 78.5% the "
    "week before. The mix has not stabilised - Agents took a further 6.6 points of landing share "
    "since the morning check. source: Contentsquare project 921964",
)

append_note(
    doc,
    "T135",
    "Update 3 Sep: the usage data this needs now partially exists",
    "Update 3 Sep: the usage data this needs now partially exists. input_tokens_lifetime, "
    "output_tokens_lifetime, requests_lifetime and spend_lifetime carry real non-zero values on 29 "
    "HubSpot contacts - the same 29 that hold API keys. The trailing 7/30/90-day windows are still "
    "zero-filled or empty, so a PQL defined on a rolling window cannot be computed yet, but a "
    "lifetime-threshold PQL can be. source: HubSpot portal 244452220, Fireflies 01M1KS84P75ZB12RAEWT5BMRSN",
)

append_note(
    doc,
    "T098",
    "Update 3 Sep: partially delivered at the session",
    "Update 3 Sep: partially delivered at the session. Grace presented peer-set benchmarks live - "
    "Radium's cost per click is running well above peers at similar spend levels, click-through rate "
    "is above peer average, and customer spend sits slightly below a six-player peer average. The "
    "deeper third-party competitive analysis did not arrive: 'I have a bigger analysis that I was "
    "hoping I would have today, but it didn't come through. Hopefully they'll get it to me tomorrow.' "
    "That piece gates general-campaign keyword expansion, which matters because Grace found the "
    "general campaign cannot spend its full daily budget on the current exact-match terms and is "
    "dipping into competitor queries to fill it - she has opened a support case on that. "
    "source: Fireflies 01M1F304TY1ARBKKWACQK1J7N4",
)

append_note(
    doc,
    "T129",
    "Update 3 Sep: priority raised medium to high",
    "Update 3 Sep: priority raised medium to high. Mona named the absence of published proof as the "
    "primary acquisition blocker on the Adam Rogers sync: there is exactly one benchmark, HAL against "
    "Opus, run internally. No third-party benchmarks, no published use cases, no case studies. Asked "
    "whether Radium has any significant accounts using it today she answered 'not that I know of', and "
    "she has no visibility into Telus at all. Her read on the audience: 'they are literally allergic to "
    "sales and marketing language, they respond well to technical and peer reviewed information.' Telus "
    "is the one real deployment there is, and this is the only task on the board that turns it into "
    "something publishable. source: Fireflies 01M1KS84P75ZB12RAEWT5BMRSN",
)


# ── 4. new tasks ─────────────────────────────────────────────────────────────
# Anchored to the epic CONTAINING a known task id, never to an epic id.
add_task(
    doc,
    "T097",  # -> p2-1 Clean up paid so it stops lying
    T(
        "T152",
        "Book the Google offline conversion call and finish enhanced conversions",
        "Grace is pulling availability for the Google offline conversion (OCI) team after her 12:00 "
        "call today and will send times for Mona to pick. This is the last step in the tracking chain: "
        "Google Tag Manager is in, signup and enhanced conversions are live, and what remains is the "
        "additional pixel that captures the PII needed to import offline conversions. Grace expects a "
        "15-20% lift in attributed conversions once it completes, and it matters more than that "
        "because it is what lets MQL be imported as a conversion action - the near-term route around "
        "T061. source: Fireflies 01M1F304TY1ARBKKWACQK1J7N4, 3 Sep",
        "Mona",
        "high",
        "2026-09-04",
        ["urgent", "data"],
        "Paid search",
        "now",
    ),
)

add_task(
    doc,
    "T097",
    T(
        "T153",
        "Finish importing and cleaning the MQL data in HubSpot before Tuesday's Google call",
        "MQL data currently sits in two places. Mona is consolidating and importing it into HubSpot: "
        "'today and tomorrow... I'll be done by tomorrow... everything is going to update by Tuesday.' "
        "The Tuesday 8 Sep call is where Google reads whether the 20-30 MQL per campaign threshold has "
        "been met, so this import is the gate on that decision rather than housekeeping. "
        "source: Fireflies 01M1F304TY1ARBKKWACQK1J7N4, 3 Sep",
        "Mona",
        "high",
        "2026-09-04",
        ["data"],
        "Paid search",
        "now",
    ),
)

add_task(
    doc,
    "T097",
    T(
        "T154",
        "Decide on 8 Sep whether to drop signup as a primary conversion action",
        "Grace set the rule: 20-30 MQLs per campaign before signup comes off as a primary conversion "
        "action, done campaign by campaign rather than account-wide, so a standout campaign can move "
        "first. Mona expects to be past 20 by the Tuesday call. Grace: 'removing that sign up as a "
        "primary conversion action and only optimizing for MQLs, that will be a really big shift for "
        "the algorithm.' This is the decision that stops paid buying free signups, and it lands on the "
        "8 Sep freeze date - changing the traffic mix after that corrupts the 15 Sep read, so it is "
        "decide-now or decide-after-the-15th. source: Fireflies 01M1F304TY1ARBKKWACQK1J7N4, 3 Sep",
        "Mona",
        "high",
        "2026-09-08",
        [],
        "Paid search",
        "now",
    ),
)

add_task(
    doc,
    "T097",
    T(
        "T155",
        "Rewrite the Built for agent workloads headline to lead with the models",
        "Leo on the Google session: the headline 'Built for agent workloads' is not particularly strong "
        "and would be much stronger as 'AI models built for agent workflows' - naming the thing being "
        "sold rather than only the use case. Grace agreed and is sending the asset report. The headline "
        "is new so its own data is thin, but it runs on the campaigns feeding /agents, which is now 58% "
        "of all site landings at 91% bounce. The ad and the first screen have to say the same thing; "
        "this is the ad half of what T113 fixes on the page. "
        "source: Fireflies 01M1F304TY1ARBKKWACQK1J7N4, 3 Sep",
        "Leo",
        "high",
        "2026-09-05",
        [],
        "Paid search",
        "now",
    ),
)

add_task(
    doc,
    "T097",
    T(
        "T156",
        "Put the Our models site link on every ad group",
        "Grace: 'Our models as a site link is doing very, very well. People are clearly interested in "
        "knowing specifically what your models look like compared to competitors. That's something I "
        "think we should have on all of your ads.' She believes it is the account default but it is "
        "worth verifying campaign by campaign. Cheapest possible win on the strongest asset in the "
        "account. source: Fireflies 01M1F304TY1ARBKKWACQK1J7N4, 3 Sep",
        "Mona",
        "medium",
        "2026-09-08",
        [],
        "Paid search",
        "now",
    ),
)

add_task(
    doc,
    "T097",
    T(
        "T157",
        "Verify the double domain and /switch path are gone from ad final URLs",
        "Leo flagged on the Google session that click URLs render the Radium domain twice and route "
        "through /switch, an old landing page that now forwards to the homepage - a redirect hop with "
        "no purpose. Grace is auditing the ads to find where it is set and taking the double-domain "
        "question to Google's measurement team to confirm it does not affect tracking; she does not "
        "expect a user-experience impact. Distinct from T062, which fixed the malformed final URL. "
        "Worth verifying rather than assuming it was picked up. "
        "source: Fireflies 01M1F304TY1ARBKKWACQK1J7N4, 3 Sep",
        "Mona",
        "medium",
        "2026-09-08",
        [],
        "Paid search",
        "now",
    ),
)

add_task(
    doc,
    "T102",  # -> p1-2 Learn from real users
    T(
        "T158",
        "Brief Adam Rogers on the product before his Paris trip",
        "Adam Rogers is being flown to Paris to represent Radium and told Mona he cannot yet explain "
        "the product: 'I'm going to Paris and I have to be able to explain this to somebody. I'm gonna "
        "set up a time with Leo for sure because I better be ready in Paris.' He put it at an hour or "
        "two to close the gaps. Mona pointed him to Leo three times on the call and said plainly she "
        "cannot cover the technical side. Leo was not on that call and nothing is booked. His laptop "
        "does not arrive until the 12th and the weekly sync in the week of 14 Sep was cancelled for the "
        "trip, so the briefing has to happen before then. Also the cheapest available source of "
        "outside-in questions: he agreed to capture what people ask in Paris. "
        "source: Fireflies 01M1KS84P75ZB12RAEWT5BMRSN, 3 Sep",
        "Leo",
        "high",
        "2026-09-09",
        [],
        "Product",
        "now",
    ),
)


# ── 5. stamp + write ─────────────────────────────────────────────────────────
if changes and doc["lastUpdated"] != TODAY:
    doc["lastUpdated"] = TODAY
    changes.append(f"lastUpdated -> {TODAY}")
elif doc["lastUpdated"] == TODAY:
    skips.append(f"lastUpdated already {TODAY}")

after_count = sum(1 for _ in all_tasks(doc))

print("── CHANGES ─────────────────────────────────────────")
for c in changes:
    print(f"  + {c}")
if not changes:
    print("  (none — everything already applied)")

print("\n── SKIPPED ─────────────────────────────────────────")
for s in skips:
    print(f"  - {s}")
if not skips:
    print("  (none)")

payload = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"

print(
    f"\n── SUMMARY ─────────────────────────────────────────\n"
    f"  tasks: {before_count} -> {after_count}\n"
    f"  changes applied: {len(changes)}\n"
    f"  changes skipped: {len(skips)}\n"
    f"  resulting JSON sha256: {hashlib.sha256(payload.encode('utf-8')).hexdigest()}"
)

if not WRITE:
    print("\nDRY RUN — nothing written. Re-run with --write to apply.")
    sys.exit(0)

if not changes:
    print("\nNothing to write.")
    sys.exit(0)

backup = DATA + ".bak-" + datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
shutil.copy2(DATA, backup)
print(f"\nBacked up to {backup}")
print("  (dashboard-data.json.bak left untouched so the watcher's rollback copy stays valid)")

with open(DATA, "w", encoding="utf-8") as f:
    f.write(payload)

with open(DATA, encoding="utf-8") as f:
    verify = json.load(f)
vcount = sum(len(e["tasks"]) for m in verify["milestones"] for e in m["epics"])
print(f"WROTE {DATA} — {vcount} tasks, lastUpdated={verify['lastUpdated']}")

# ── sweep sibling copies ─────────────────────────────────────────────────────
# If an earlier build of this patch ran here, its text may also sit in a backup
# or in the built dist/ copy. Scrub those in place rather than leaving them.
sweep_targets = []
bak_dir = os.path.dirname(DATA)
if os.path.isdir(bak_dir):
    for name in sorted(os.listdir(bak_dir)):
        if name.startswith("dashboard-data.json.bak"):
            sweep_targets.append(os.path.join(bak_dir, name))
sweep_targets.append(os.path.join("dist", "data", "dashboard-data.json"))

for target in sweep_targets:
    if not os.path.isfile(target):
        continue
    try:
        with open(target, encoding="utf-8") as f:
            sub = json.load(f)
    except (OSError, json.JSONDecodeError):
        continue
    touched = False
    for _m, _e, t in all_tasks(sub):
        if t["id"] in SCRUB_IDS and scrub_task(t):
            touched = True
    if not touched:
        continue
    with open(target, "w", encoding="utf-8") as f:
        f.write(json.dumps(sub, indent=2, ensure_ascii=False) + "\n")
    print(f"  swept {target}")
