#!/usr/bin/env python3
"""
Radium PLG tracker patch - 3 Sep 2026
Generated by the nightly Claude run (cloud; no filesystem/MCP access to the board).

Usage, from inside radium-command-center/:
    python3 apply-2026-09-03.py            # dry run, prints what would change
    python3 apply-2026-09-03.py --write    # applies, backs up to dashboard-data.json.bak

Idempotent: safe to run twice. Notes are keyed on "Update 3 Sep" / "Note 3 Sep",
new tasks are keyed on task id.

Epics are located by walking to the epic that CONTAINS a known task id, never by
epic id, so a renamed or re-ordered epic still resolves correctly.
"""
import json, os, shutil, sys

PATH = "public/data/dashboard-data.json"
WRITE = "--write" in sys.argv

# ---------------------------------------------------------------- helpers
def find_task(data, tid):
    for m in data["milestones"]:
        for e in m["epics"]:
            for t in e["tasks"]:
                if t["id"] == tid:
                    return m, e, t
    return None, None, None

def epic_containing(data, tid):
    m, e, _ = find_task(data, tid)
    return m, e

changes, skipped = [], []

def append_note(tid, key, note):
    _, _, t = find_task(data, tid)
    if t is None:
        skipped.append(f"{tid}: not found on the board - skipped"); return
    if key in t["description"]:
        skipped.append(f"{tid}: note already present - skipped"); return
    t["description"] = t["description"].rstrip() + " " + note
    changes.append(f"{tid}  append note   {t['title'][:58]}")

def set_priority(tid, old, new):
    _, _, t = find_task(data, tid)
    if t is None:
        skipped.append(f"{tid}: not found on the board - skipped"); return
    if t["priority"] == new:
        skipped.append(f"{tid}: priority already {new} - skipped"); return
    if t["priority"] != old:
        skipped.append(f"{tid}: priority is '{t['priority']}', expected '{old}' - SKIPPED, check by hand"); return
    t["priority"] = new
    changes.append(f"{tid}  priority {old} -> {new}   {t['title'][:44]}")

def add_task(anchor_tid, task):
    if find_task(data, task["id"])[2] is not None:
        skipped.append(f"{task['id']}: already exists - skipped"); return
    m, e = epic_containing(data, anchor_tid)
    if e is None:
        skipped.append(f"{task['id']}: anchor {anchor_tid} not found - SKIPPED"); return
    e["tasks"].append(task)
    changes.append(f"{task['id']}  NEW -> {m['id']}/{e['id']}   {task['title'][:52]}")

def T(tid, title, desc, assignee, priority, due, channel, bucket="now", tags=None):
    return {"id": tid, "title": title, "description": desc, "completed": False,
            "assignee": assignee, "priority": priority, "dueDate": due,
            "tags": tags or [], "channel": channel, "bucket": bucket}

# ---------------------------------------------------------------- load
if not os.path.exists(PATH):
    sys.exit(f"Cannot find {PATH} - run this from inside radium-command-center/")
with open(PATH) as f:
    data = json.load(f)

FF_ENG  = "Fireflies 01M0ZG5SJZSHETYYAV41F0QN6Z"   # Engineering <> Marketing Sync, 2 Sep
FF_CONT = "Fireflies 01M0ZG5SJTFYDYRAMWC15M0BJT"   # Content/Editorial Weekly, 2 Sep
FF_XADS = "Fireflies 01M0ZG5SK17AQKGEFJ0ERYGNG6"   # X Ads Consultation, 2 Sep

# ---------------------------------------------------------------- 1. notes
append_note("T019", "Update 3 Sep",
  "Update 3 Sep: no movement. Re-checked HubSpot portal 244452220 - "
  "first_api_key_created_date is still empty on every record, first_api_request_date is still on 3 "
  "contacts (Jun/Jul), api_key_count is on 29 records, down one from 30. The 2 Sep due date has "
  "passed and the description's own trigger (escalate to Adam on 2 Sep) fired. Engineering "
  "leadership was in the room at the 2 Sep Engineering <> Marketing sync and product events were "
  "not raised; Vijay declined the invite. source: HubSpot 3 Sep; " + FF_ENG)

append_note("T022", "Update 3 Sep",
  "Update 3 Sep: the Offline/integration feed that creates this pollution has gone near-silent. "
  "Daily contacts with source detail 'integration': roughly 150/day every weekday 4-20 Aug, then "
  "6 and 3 on 21 and 24 Aug, then 102/104/91 on 25-27 Aug, then 5, 0, 0, 2, 2, 2 from 28 Aug to "
  "2 Sep. Stripping them from reporting is still right, but establish whether the feed was turned "
  "off deliberately or broke before treating the drop as a clean-up win - if it broke, product "
  "signups are no longer reaching HubSpot at all. source: HubSpot 3 Sep")

append_note("T011", "Update 3 Sep",
  "Update 3 Sep: the first instance of this motion is already in flight. Leo is booking a recorded "
  "engineer-to-engineer call with a lead engineer at Peer (an AEO product company) who installed "
  "and tested Radium, compensated with free credits. Alex named the attendees: Vijay, Alex, Joey "
  "and Scott, Joey optional, and asked that it not wait on Vijay's calendar. Priority deliberately "
  "left where Leo set it on 2 Sep. source: " + FF_ENG)

append_note("T009", "Update 3 Sep",
  "Update 3 Sep: Alex reports the whole engineering team is now testing models daily rather than "
  "just DJ and Joey, and is generating a steady list of things to fix - his words, 'we are the "
  "users of our own system'. He also cannot get HAL working in Cursor at all. Internal adoption is "
  "happening but the friction it is surfacing is real, so this stays blocked. source: " + FF_ENG)

append_note("T070", "Note 3 Sep",
  "Note 3 Sep: a candidate artefact surfaced on the 2 Sep sync - a Claude Code skill that sets up "
  "Radium end to end. It came from the Peer engineer's feedback and Alex costed it at roughly a "
  "couple of hours plus testing. It is the cheapest thing on this list that removes real setup "
  "friction. source: " + FF_ENG)

# ---------------------------------------------------------------- 2. priority
set_priority("T068", "low", "medium")

# ---------------------------------------------------------------- 3. new tasks
add_task("T011", T("T102",
  "Send the Peer engineer feedback notes to Alex for internal distribution",
  "Alex asked twice on the 2 Sep sync not to keep these notes to Vijay - he wants them emailed to "
  "him so he can distribute them and compare against the team's own internal feedback. Leo "
  "confirmed the notes are written up. One email. The notes cover: the OpenAI responses API URL "
  "change, guardrails being too strong on HAL in places, a request for reasoning-effort levels and "
  "UI context-window control, a suggestion to push Claude Code mode because the model is fast, a "
  "Claude Code setup skill, and the isolated-instance setup that took him 30 minutes. source: " + FF_ENG,
  "Leo", "high", "2026-09-03", "Product", "now", ["urgent"]))

add_task("T011", T("T103",
  "Book the engineer-to-engineer feedback call with the Peer lead engineer",
  "Leo committed on the 2 Sep sync to get a 30-minute call in the calendar and said he did not "
  "want it slipping past the long weekend. Attendees per Alex: Vijay, Alex, Joey, Scott - Joey "
  "optional, and Alex said do not delay it a week to catch Vijay, he can read the Fireflies. Avoid "
  "noon Eastern Monday, 2pm Wednesday, and Friday engineering catch-ups. The engineer is a lead at "
  "Peer, an AEO product company, and is being paid in free credits for the time. source: " + FF_ENG,
  "Leo", "high", "2026-09-04", "Product", "now", ["urgent"]))

add_task("T068", T("T104",
  "Get Radium listed in the model dropdowns developers actually use",
  "Leo found Cohere in the Cline provider dropdown and no Radium, and could not get Radium working "
  "through Continue at all - he had to pick 'OpenAI compatible' in Cline and paste the key by hand. "
  "Alex confirmed this is not a technical fix on our side and that making it one-click would help "
  "adoption 'without a freaking doubt'. Two routes he named: a business arrangement for the "
  "commercial tools (Cursor, Fireflies), and for the more open ones (Metabase has a request form) "
  "just ask them to add it. Third option: publish a downloadable JSON config people can drop in. "
  "Alex has been arguing for a partnership function for two weeks; this is the concrete first job "
  "for it. source: " + FF_ENG,
  "Leo", "medium", "2026-09-22", "Partnerships", "next"))

add_task("T036", T("T105",
  "Write the isolated-instance test guide so people can try Radium without touching their setup",
  "The single item the Peer engineer weighted highest. He needed an isolated Claude instance to "
  "benchmark Radium without disturbing his existing Claude Code setup, and it cost him about 30 "
  "minutes to work out. He was not asking us to build anything - just to document it. Alex did the "
  "same thing on his Mac and wrote a script for the Cursor equivalent, though that one involves "
  "poking at Cursor's databases so it may be better published as a prompt than as instructions. "
  "This is the doc that lets someone evaluate without committing. Needs engineering input to "
  "write. source: " + FF_ENG,
  "Leo", "medium", "2026-09-22", "Docs", "next"))

add_task("T011", T("T106",
  "Build the HubSpot feedback form and opt-in segmentation",
  "Mona is running this end to end and has done it before at a previous company: a form on the "
  "site, respondents categorised by role and experience, opt-in recorded in HubSpot so specific "
  "groups can be approached for specific product questions. Compensation is credits or a gift "
  "card. She has already outlined the form. This is the machinery that makes T011's feedback "
  "contract repeatable rather than one-off. source: " + FF_CONT,
  "Mona", "high", "2026-09-04", "CRM", "now"))

add_task("T011", T("T107",
  "Add incentives to Mona's feedback form draft and approve the send",
  "Mona said on the 2 Sep call she would send the feedback form draft to Leo within minutes, for "
  "Leo to add the incentive details before it goes out to everyone who has already used the "
  "platform. Small task, but the send is blocked on it and the draft is already sitting in the "
  "inbox. source: " + FF_CONT,
  "Leo", "high", "2026-09-03", "CRM", "now", ["urgent"]))

add_task("T057", T("T108",
  "Decide whether to double the X campaign budget before the credits expire",
  "The @RadiumAi campaign was not serving at all until Osama had Mona enable optimised targeting "
  "on the 2 Sep call; it began delivering during the call and passed 200 impressions. Budget is "
  "$4,000. Leo raised doubling it to reach $5,000 of spend inside two weeks and unlock the matching "
  "ad credits, which expire at the end of September. Mona moved the campaign end date to 16 Sep. "
  "Keep optimised targeting on through the 3-5 day learning phase unless performance is bad. Note "
  "the budget-control interaction: roughly $23k is already committed against $20k approved, so this "
  "decision belongs in the same conversation as T005 and T008. source: " + FF_XADS,
  "Leo", "high", "2026-09-04", "Paid social", "now"))

add_task("T057", T("T109",
  "Review X campaign performance with Osama on 8 Sep",
  "Booked on the 2 Sep call. Osama is monitoring delivery, spend, impressions, clicks and any "
  "further serving blocks through the week and will bring recommendations. Also outstanding from "
  "him: whether the lead-generation beta has rolled out, which would let the campaign capture "
  "leads directly rather than through the current email-only signup form. source: " + FF_XADS,
  "Mona", "medium", "2026-09-08", "Paid social", "now"))

# ---------------------------------------------------------------- report + write
data["lastUpdated"] = "2026-09-03"

print("=" * 78)
print("Radium tracker patch - 3 Sep 2026" + ("  [WRITE]" if WRITE else "  [DRY RUN]"))
print("=" * 78)
for c in changes:
    print("  " + c)
if skipped:
    print("\n  skipped:")
    for s in skipped:
        print("    " + s)
total = sum(len(e["tasks"]) for m in data["milestones"] for e in m["epics"])
print(f"\n  {len(changes)} change(s); board would hold {total} tasks; lastUpdated -> 2026-09-03")

if WRITE:
    if changes:
        shutil.copy(PATH, PATH + ".bak")
        with open(PATH, "w") as f:
            json.dump(data, f, indent=2)
            f.write("\n")
        print(f"\n  written. backup at {PATH}.bak")
    else:
        print("\n  nothing to write.")
else:
    print("\n  dry run - nothing written. re-run with --write to apply.")
